# `AA Workshop 03` - Libraries: NumPy & Pandas

In this tutorial we will introduce the concept of Python libraries and cover two very important such library - NumPy.

We will go through the following:

- Python dictionary and lists comprehensions
- Introduction to the concept of `Python Libraries`
- Introduction to `NumPy`
- Introduction to `Pandas`

---

## Python Iterable Comprehensions

Comprehensions are a method for transforming one iterable into another iterable. During this transformation, items within the original iterable can be conditionally included in the new one and each item can be transformed as needed. Comprehensions are a powerful concept and can be used to substitute `for loops` and `lambda functions`. However, not all `for loops` can be written as a comprehension but all comprehensions can be written with a `for loop`. (We will talk about `lambda functions` in future workshops).

A good comprehension can make your code more expressive and, thus, easier to read. The key with creating comprehensions is to not let them get so complex that your head spins when you try to decipher what they are actually doing. Keeping the idea of *easy to read* alive.

The general template you can follow for comprehensions in Python is:

`dict_variable = {key:value for (key,value) in dictonary.items()}`

`list_variable = [value for value in list]`

In [1]:
dict1 = {'a':1, 'b':2, 'c':3, 'd':4}

Remeber that with the `items()` method you can access each key-value pair in a dictionary. You can access the values and keys in a dictionary by using `values()` and `keys()`, respectively.

In [2]:
print(dict1.items())
print(dict1.values())
print(dict1.keys())

dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 4)])
dict_values([1, 2, 3, 4])
dict_keys(['a', 'b', 'c', 'd'])


Here are some examples of dictionary comprehensions:

In [3]:
# ^2 each value in the dictionary
new_dict1 = {k:v**2 for (k,v) in dict1.items()}
print(new_dict1)

{'a': 1, 'b': 4, 'c': 9, 'd': 16}


In [4]:
# exchange keys and values
new_dict2 = {v:k for (k,v) in dict1.items()}
print(new_dict2)

{1: 'a', 2: 'b', 3: 'c', 4: 'd'}


In [5]:
# change the keys of the original dictionary
new_dict3 = {k+'a':v for (k,v) in dict1.items()}
print(new_dict3)

{'aa': 1, 'ba': 2, 'ca': 3, 'da': 4}


### Conditional Comprehesions

Consider the following problem: you want to create a new dictionary with even numbers in a range of 0-10 as keys and the square of the number as values. One solution is to use a `for` loop. Another solution is to use dictionary comprehension method as follows:

In [6]:
new_dict4 = {n:n**2 for n in range(10) if n%2 == 0}
print(new_dict4)

{0: 0, 2: 4, 4: 16, 6: 36, 8: 64}


You can do the same with any other iterable, especially lists:

In [7]:
ls1 = [i for i in range(10)]
ls1

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [8]:
ls2 = [str(i**2) for i in range(10) if i%3==0 ]
print(ls2)

['0', '9', '36', '81']


In [9]:
quote = "life, uh, finds a way"
unique_vowels = {i for i in quote if i in 'aeiou'}
vowels = [i for i in quote if i in 'aeiou']
print(unique_vowels)
print(vowels)

{'i', 'u', 'e', 'a'}
['i', 'e', 'u', 'i', 'a', 'a']


---

## `Python Libraries`

**Introduction to Libraries**

A library (or module, or package) is a Python object with arbitrarily named attributes that you can bind and reference. Simply, a module is a file consisting of Python code. A module can define functions, classes and variables. A module can also include runnable code.

You can use any Python source file as a module by executing an import statement in some other Python source file. The import has the following syntax:


```
import <module name>
```

By convention it is common to name modules so they can be called by entering an abbreviated name. This is effectively importing the module in the same way that `import <module name>` will do, with the only difference of it being available as ` <module name abbreviation>`. In the case of `numpy`, for example, the abbreviation `np`is used.

```
import <module name> as <module name abbreviation>
```


In [10]:
# import numpy
import numpy as np

**Adding/Installing Libraries**

To add Python libraries to your installation you can use the `conda` package manager that we have installed in the last workshop. Alternatively you can also use the `pip` package manager. The quickest way to do so is via a terminal:

* If you are on a **Windows** computer, use the "Anaconda Command Prompt" from the Start menu. 
* On a **Mac**, start up the "Terminal". 
* In **Linux**, use any of the terminals available.


The gerneral command syntax is the following:

```
conda install <package name>
```

If you are looking for a specific package but are unsure of the exact command line name do a quick google search and/or check the [Anaconda Cloud](https://anaconda.org). Another approach to find the exact name of a package before installation is using the conda search command in terminal; the syntax is the following:

```
conda search <name>
```


**Relevant Libraries for this course**

There is a large variety of open source libraries available in Python. Below is a list of some of the most relevant ones for data science, which will be covered in this course.

* Selected data science libraries

    * Data Analysis and Processing
    >* Pandas (pd)
    >* Numpy (np)
    * Visualization        
    >* matplotlib and pyplot (plt)
    >* seaborn (sns)
    * Models and methods
    >* Scikit Learn (sklearn)
    >* statsmodels

**Executing commands from within Jupyter:** For your convenience, it is possible to execute commands from within Jupyter cells using a line prefixed with `!`.
In the example, we list (`ls`) the current working directory, and format it for human-readable output (`-h`) and to include more detail (`-l`). Commands are executed in the local user shell and in the conda environment that the notebook uses.

In [ ]:
!ls -lh

---

## `NumPy`

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- A powerful N-dimensional array object
- Sophisticated (broadcasting) functions
- Tools for integrating C/C++ and Fortran code
- Useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

NumPy’s main object is the homogeneous multidimensional array. It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In NumPy, dimensions are called axes. The number of axes is rank.

In today's short overview tutorial we will cover the following:

1. **Creating NumPy Arrays**
1. **Modifying (manipulating) NumPy Arrays**
1. **NumPy Array Oprations**

Let's get started...

### Creating NumPy Arrays

First, we can use `np.array` to create arrays from python lists. Unlike Python lists, **NumPy is constrained to arrays that all contain the same type**. If types don't match, NumPy will upcast if possible. 

In [12]:
A = np.array([1,2,3,4,5])
A

array([1, 2, 3, 4, 5])

In [13]:
B = np.array([3.1, 5, 4, 6])
B

array([3.1, 5. , 4. , 6. ])

In [14]:
D =np.array([1,2,'a',3])
D

array(['1', '2', 'a', '3'], dtype='<U21')

Read more info in greater details about string types and other datatype objects in the [numpy documentation](https://numpy.org/doc/stable/reference/arrays.dtypes.html).

If we want to explicitly set the data type of the resulting array, we can use the `dtype` keyword.

In [15]:
C = np.array([1,2,3,8],dtype = float)
print (C)

[1. 2. 3. 8.]


Other examples of creating arrays using np functions:

In [16]:
# create vector of length 5 filled with zeros
E = np.zeros(5,dtype = float)

# create 2x4 matrix of ones (float)
F = np.ones((2,4), dtype= float)

# create vector from 0-12 in steps of 2
G = np.arange(0,12,2)

# create vector from 0 to 1 with five equally (linearly) spaced elements 
H = np.linspace(0,1,5)

# create a 2x2 matrix with random floats in the half-open interval [0.0, 1.0)
I = np.random.random((2,2))

# return random integers from 0 (inclusive) to 10 (exclusive) of size (4,3,2)
J = np.random.randint (0,10,(4,3,2))

print("E =", E,
      "\n\nF =", F, 
      "\n\nG =", G, 
      "\n\nH =", H, 
      "\n\nI =", I, 
      "\n\nJ =", J)

E = [0. 0. 0. 0. 0.] 

F = [[1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

G = [ 0  2  4  6  8 10] 

H = [0.   0.25 0.5  0.75 1.  ] 

I = [[0.33813332 0.22926955]
 [0.49224697 0.15517295]] 

J = [[[5 6]
  [5 9]
  [5 1]]

 [[7 6]
  [2 4]
  [2 9]]

 [[1 3]
  [3 8]
  [5 9]]

 [[5 6]
  [9 7]
  [4 1]]]


### Modifying (manipulating) NumPy Arrays

Data manipulation in Python is nearly synonymous with NumPy array manipulation. We will cover a few categories of basic array manipulations here:
- **Attributes of arrays**: Determinig the size, shape, memory consumption and data type of arrays.
- **Indexing of arrays**: Getting and setting the value of indivisual array elements.
- **Slicing of arrays**: Getting and setting smaller subarrays within a larger array.
- **Reshaping of arrays**: Changing the shape of a given array.
- **Joining and splitting of arrays**: Combining multiple arrays into one, and splitting one array into many.

#### NumPy Array Attributes:
In the following some examples on attributes are presented.

In [18]:
# returns dimension
print("E ndim: ", E.ndim)

# returns shape in form (#row,#col)
print("F sahpe: " , F.shape)

# returns size (i.e. no of elements)
print("J size: ", J.size)

# returns data type
print("H dtype: ", H.dtype)

# returns length of one array element in bytes
print("itemsize: ", I.itemsize," bytes")

# returns total bytes consumed by the elements of the array
print("nbytes:  ", I.nbytes, "bytes")

E ndim:  1
F sahpe:  (2, 4)
J size:  24
H dtype:  float64
itemsize:  8  bytes
nbytes:   32 bytes


#### NumPy Array Indexing

You can easily access single elements as you already know from Python:

In [19]:
# this is the full array
A

array([1, 2, 3, 4, 5])

In [20]:
print("The 4th element of A is {}". format(A[3]))
print("The last element of A is {}". format(A[-1])) # index from the back

The 4th element of A is 4
The last element of A is 5


In a multidimensional array (i.e. a matrix), you access items using a comma-seperated tuple of indices.

In [21]:
# remember multidimensional array I
I

array([[0.33813332, 0.22926955],
       [0.49224697, 0.15517295]])

In [22]:
print ("The first element of I is {}". format(I[0,0]))  #array[row,column]
print ("The last element of I is {}". format(I[1,1]))   #array[row,column]

The first element of I is 0.33813331932680823
The last element of I is 0.15517295104209483


#### NumPy Array Slicing:

**One-dimensional arrays**

Just as we can use square brakets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon `:` character. The syntax is as follow:

` X[start (incl.):stop (excl.):step]`

In [23]:
# remember array G
G

array([ 0,  2,  4,  6,  8, 10])

In [24]:
print("middle subarray:", G[2:4])
print("First 4 elemnts:", G[:5])
print("Last 3 elements:", G[-3:] )
print("Every other element:", G[::2])
print("All elements reversed:", G[::-1])

middle subarray: [4 6]
First 4 elemnts: [0 2 4 6 8]
Last 3 elements: [ 6  8 10]
Every other element: [0 4 8]
All elements reversed: [10  8  6  4  2  0]


**Multi-dimensional arrays**

Multi-dimensional slices work in the same way, with multiple slices seperated by commas. The command is: 

`X[slice row, slice column]`

In [33]:
# create a multi-dimensional array K
K = np.random.randint(0,20, (3,4))
K

array([[ 9,  5, 19, 15],
       [ 8,  3,  8, 12],
       [18,  4, 17,  8]])

In [34]:
print ("The first two rows and the first three column: \n", K[:2,:3])
print("All rows and every other column:\n", K[:,::2])
print("All rows and columns reversed:\n",K[::-1,::-1] )

The first two rows and the first three column: 
 [[ 9  5 19]
 [ 8  3  8]]
All rows and every other column:
 [[ 9 19]
 [ 8  8]
 [18 17]]
All rows and columns reversed:
 [[ 8 17  4 18]
 [12  8  3  8]
 [15 19  5  9]]


#### NumPy Array Reshaping:

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. Note that for this to work, the size of the initial array must match the size of the reshaped array.

In [35]:
# return evenly spaced values within a given interval
Y = np.arange(1,25)
Y

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [36]:
len(Y)

24

In [37]:
# we can re-shape this array into any shape with 24 elements
Y.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

Similarly, you can easily transpose multi-dimensional arrays using `T`:

In [38]:
# remember K
K

array([[ 9,  5, 19, 15],
       [ 8,  3,  8, 12],
       [18,  4, 17,  8]])

In [39]:
# transpose K
K.T

array([[ 9,  8, 18],
       [ 5,  3,  4],
       [19,  8, 17],
       [15, 12,  8]])

#### NumPy Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays.

**Concatenation of arrays**

Concatenation, or joining of two arrays in NumPy, is primarily accomplished using the routine `np.concatenate`. Additionally `np.vstack`, and `np.hstack` may be used.

In [40]:
# one-dimensional
P = np.array([1,2,3])
Q = np.array([4,5,6])
np.concatenate((P,Q))

array([1, 2, 3, 4, 5, 6])

In [41]:
# multi-dimensional
R = np.array([[3,5,7],[1,3,5]])
S = np.array([[2,4,2],[0,9,8]])
print(R, "\n")
print(S)

[[3 5 7]
 [1 3 5]] 

[[2 4 2]
 [0 9 8]]


In [42]:
# pass the axis along which the arrays should be joined
print(np.concatenate((R,S), axis = 0), "\n")
print(np.concatenate((R,S), axis = 1), "\n")

[[3 5 7]
 [1 3 5]
 [2 4 2]
 [0 9 8]] 

[[3 5 7 2 4 2]
 [1 3 5 0 9 8]] 



For working with arrays of mixed dimensions, it can be more practical to use the `np.vstack` (vertical stack) and `np.hstack` (horizontal stack) functions:

In [43]:
# stack row-wise
np.vstack((R,S))

array([[3, 5, 7],
       [1, 3, 5],
       [2, 4, 2],
       [0, 9, 8]])

In [44]:
# stack column-wise
np.hstack((R,S))

array([[3, 5, 7, 2, 4, 2],
       [1, 3, 5, 0, 9, 8]])

**Splitting of arrays**

The opposite of concatenation is splitting, which is implemented by the functions `np.split`, `np.hsplit`, and `np.vsplit`. For each of these, we can pass a list of indices indicating the split points:

In [45]:
# divides the array x into 4 equal subarrays
x = np.array([2,4,6,7,8,9,1,3,11,35,55,34])
print(np.split(x,4))

[array([2, 4, 6]), array([7, 8, 9]), array([ 1,  3, 11]), array([35, 55, 34])]


In [46]:
x1, x2, x3, x4 = np.split(x,4)
print(x1, x2, x3, x4)

[2 4 6] [7 8 9] [ 1  3 11] [35 55 34]


In [47]:
# create multi-dimensional array
Z = np.arange(16).reshape((4, 4))
Z

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
# splits array Z into multiple sub-arrays vertically (row-wise)
upper, lower = np.vsplit(Z, 2)
print("upper: \n",upper)
print("lower: \n",lower)

upper: 
 [[0 1 2 3]
 [4 5 6 7]]
lower: 
 [[ 8  9 10 11]
 [12 13 14 15]]


In [49]:
# splits array Z into multiple sub-arrays horizontally (column-wise)
left, right = np.hsplit(Z, 2)
print("left: \n",left)
print("right: \n",right)

left: 
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
right: 
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


### NumPy Array Operations

Numpy also allows for **element-wise** as well as linear algebra **matrix-type** operations, which are a key component of scientific computing tasks.

In [50]:
# create two one-dimensional arrays
A = np.array([1,2,3,4])
B = np.array([9,3,-9,6])

**Element-wise operations**

In [51]:
# element-wise addition
C=A+B
C

array([10,  5, -6, 10])

In [52]:
# element-wise substraction
D=A-B
D

array([-8, -1, 12, -2])

In [53]:
# element-wise multiplication
E=A*B
E

array([  9,   6, -27,  24])

In [54]:
# element-wise division
F=A/B
F

array([ 0.11111111,  0.66666667, -0.33333333,  0.66666667])

**Matrix operations**

In [56]:
# create two 2x5 matrices
M = np.arange(10).reshape(2,5)
N = np.random.randint(1,10,10).reshape(2,5)
print(M, "\n")
print(N)

[[0 1 2 3 4]
 [5 6 7 8 9]] 

[[3 2 4 3 3]
 [3 5 2 9 8]]


In [ ]:
# note: performing a matrix multiplication on two 2x5 matrices is not possible
M@N

In [58]:
# We can transpose one of the matrices to obtain a 5x2 matrix, then the operation works
M@N.T

array([[ 31,  68],
       [106, 203]])

---


## `Pandas`

Pandas is a newer package built on top of `NumPy`, and provides an efficient implementation of a `DataFrame`, the core Pandas object. DataFrames are essentially multidimensional arrays with attached row and column labels, and often with heterogeneous types and/or missing data. As well as offering a convenient storage interface for labeled data, Pandas implements a number of powerful data operations familiar to users of both database frameworks and spreadsheet programs. We will use `Pandas` as the main tool to structure, manipulate and store data throughout this course. As such, Pandas constitutes a core data science library that all of you should be very well familiar with.

Let's get started by importing pandas.

In [59]:
import pandas as pd

### Introduction to `Pandas` objects

At the very basic level, Pandas objects can be thought of as enhanced versions of NumPy structured arrays in which the rows and columns are identified with labels rather than simple integer indices. Pandas provides a host of useful tools, methods, and functionality on top of the basic data structures, but nearly everything that follows will require an understanding of what these structures are. Thus, before we go any further, let's introduce these three fundamental Pandas data structures: the Series, DataFrame, and Index.



#### The `Pandas Series` Object
A Pandas Series is a one-dimensional array of indexed data. It can be created from a list or array as follows:

In [60]:
A = [12,13,14,15,16,17]
A

[12, 13, 14, 15, 16, 17]

In [61]:
F = pd.Series(A)
F

0    12
1    13
2    14
3    15
4    16
5    17
dtype: int64

As we see in the output, the Series wraps both a sequence of values and a sequence of indices, which we can access with the values and index attributes. The values are simply a familiar NumPy array:

In [62]:
F.values

array([12, 13, 14, 15, 16, 17])

The index is an array-like object of type pd.Index, which we'll discuss in more detail later.

In [63]:
F.index

RangeIndex(start=0, stop=6, step=1)

Like with a `NumPy` array, data can be accessed by the associated index via the familiar Python square-bracket notation:

In [64]:
print(F[2])

14


In [65]:
print(F[2:5])

2    14
3    15
4    16
dtype: int64


From what we've seen so far, it may look like the Series object is basically interchangeable with a one-dimensional NumPy array. **The essential difference is the presence of the index**: while the Numpy Array has an implicitly defined integer index used to access the values, the Pandas Series has an explicitly defined index associated with the values.
This explicit index definition gives the Series object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type. For example, if we wish, we can use strings as an index:


In [66]:
C = pd.Series([0.25, 0.5, 0.75, 1.0],index=['a', 'b', 'c', 'd'])
C

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [67]:
print(C['c'])

0.75


In this way, you can think of a Pandas Series a bit like a specialization of a Python dictionary. A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a Series is a structure which maps typed keys to a set of typed values. This typing is important: just as the type-specific compiled code behind a NumPy array makes it more efficient than a Python list for certain operations, the type information of a Pandas Series makes it much more efficient than Python dictionaries for certain operations.
The Series-as-dictionary analogy can be made even more clear by constructing a Series object directly from a Python dictionary:

In [68]:
population_dict = {'California': 38332521,
                   'Texas': 2644819,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas          2644819
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

Unlike a dictionary, though, the Series also supports array-style operations such as slicing:

In [69]:
population_dict.keys()

dict_keys(['California', 'Texas', 'New York', 'Florida', 'Illinois'])

In [ ]:
# slicing a dict does not work
population_dict['California':'New York']

In [71]:
# slicing a Series object works
population['California':'New York']

California    38332521
Texas          2644819
New York      19651127
dtype: int64

#### The `Pandas DataFrame` Object

The next fundamental structure in `Pandas`  is the `DataFrame` . Like the Series object discussed in the previous section, the DataFrame can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary. We'll now take a look at each of these perspectives.

If a Series is an analog of a one-dimensional array with flexible indices, a DataFrame is an analog of a two-dimensional array with both flexible row indices and flexible column names. Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a DataFrame as a sequence of aligned Series objects. Here, by "aligned" we mean that they share the same index.

In [72]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64


Now that we have this along with the population Series from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [73]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

population    area
California    38332521  423967
Texas          2644819  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

Like the Series object, the DataFrame has an index attribute that gives access to the index labels:

In [74]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

Additionally, the DataFrame has a columns attribute, which is an Index object holding the column labels:

In [75]:
states.columns

Index(['population', 'area'], dtype='object')

Thus, the DataFrame can be thought of as a generalization of a two-dimensional NumPy array, where both the rows and columns have a generalized index for accessing the data.

#### The `Pandas Index` Object

We have seen here that both the Series and DataFrame objects contain an explicit index that lets you reference and modify data. This Index object is an interesting structure in itself, and it can be thought of either as an immutable array or as an ordered set (technically a multi-set, as Index objects may contain repeated values). Those views have some interesting consequences in the operations available on Index objects. As a simple example, let's construct an Index from a list of integers:

In [76]:
ind = pd.Index([2, 3, 5, 7, 11])
ind

Index([2, 3, 5, 7, 11], dtype='int64')

The Index in many ways operates like an array. For example, we can use standard Python indexing notation to retrieve values or slices:

In [77]:
ind[0]

np.int64(2)

In [78]:
ind[::2] # every second object starting at 0

Index([2, 5, 11], dtype='int64')

Index objects also have many of the attributes familiar from NumPy arrays:

In [79]:
print(ind.size, ind.shape, ind.ndim, ind.dtype)

5 (5,) 1 int64


One difference between Index objects and NumPy arrays is that indices are immutable – that is, they cannot be modified via the normal means.

In [ ]:
# this does not work with index objects
ind[1] = 0

### Data selection in `Pandas`

#### Data Selection in Series

As we saw in the previous section, a Series object acts in many ways like a one-dimensional NumPy array, and in many ways like a standard Python dictionary. If we keep these two overlapping analogies in mind, it will help us understand the patterns of data indexing and selection in these arrays.

Like a dictionary, the Series object provides a mapping from a collection of keys (i.e. the index) to a collection of values:

In [81]:
C

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [82]:
print(C['d'])

1.0


We can also use dictionary-like Python expressions and methods to examine the keys/indices and values:

In [83]:
C.keys()

Index(['a', 'b', 'c', 'd'], dtype='object')

In [84]:
list(C.items())

[('a', 0.25), ('b', 0.5), ('c', 0.75), ('d', 1.0)]

Series objects can even be modified with a dictionary-like syntax. Just as you can extend a dictionary by assigning to a new key, you can extend a Series by assigning to a new index value:


In [85]:
# add value
C['e'] = 1.25
C

a    0.25
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [86]:
# change value
C['a'] = 0
C

a    0.00
b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

A Series builds on this dictionary-like interface and provides array-style item selection via the same basic mechanisms as NumPy arrays – that is, slices, masking, and fancy indexing. Examples of these are as follows:

In [87]:
# slicing by explicit index (note: including last)
C['a':'c']

a    0.00
b    0.50
c    0.75
dtype: float64

In [88]:
# slicing by implicit integer index (note: excluding last)
C[0:2]

a    0.0
b    0.5
dtype: float64

In [89]:
C[C>=0.5]

b    0.50
c    0.75
d    1.00
e    1.25
dtype: float64

In [90]:
# masking
C[(C > 0.3) & (C < 0.8)]

b    0.50
c    0.75
dtype: float64

In [92]:
# multiple indexing
C[['a', 'e', "c"]]

a    0.00
e    1.25
c    0.75
dtype: float64

Among these, slicing may be the source of the most confusion. Notice that when slicing with an explicit index (i.e., data['a':'c']), the final index is included in the slice, while when slicing with an implicit index (i.e., data[0:2]), the final index is excluded from the slice.

**Indexers: loc and iloc**

These slicing and indexing conventions can be a source of confusion. For example, if your Series has an explicit integer index, an indexing operation such as data[1] will use the explicit indices, while a slicing operation like data[1:3] will use the implicit Python-style index.

In [93]:
data = pd.Series(['a', 'b', 'c', 'd'], index=[1, 3, 5,7])
data

1    a
3    b
5    c
7    d
dtype: object

In [94]:
# explicit index when indexing
data[5]

'c'

In [95]:
# implicit index when slicing
data[1:3]

3    b
5    c
dtype: object

Because of this potential confusion in the case of integer indexes, Pandas provides some special indexer attributes that explicitly expose certain indexing schemes. These are not functional methods, but attributes that expose a particular slicing interface to the data in the Series.
First, the `.loc` attribute allows indexing and slicing that always references the **explicit index**:

In [96]:
data.loc[1]

'a'

In [97]:
data.loc[1:3]

1    a
3    b
dtype: object

The `.iloc` attribute allows indexing and slicing that always references the **implicit Python-style index**:

In [98]:
data.iloc[1]

'b'

In [99]:
data.iloc[1:3]

3    b
5    c
dtype: object

One guiding principle of Python code is that **"explicit is better than implicit"**. The explicit nature of `.loc` and `.iloc` make them very useful in maintaining clean and readable code; especially in the case of integer indexes, I recommend using these both to make code easier to read and understand, and to prevent subtle bugs due to the mixed indexing/slicing convention.

#### Data Selection in DataFrame

Recall that a DataFrame acts in many ways like a two-dimensional or structured array, and in other ways like a dictionary of Series structures sharing the same index. These analogies can be helpful to keep in mind as we explore data selection within this structure.

In [100]:
area = pd.Series({'California': 423967, 'Texas': 695662,
                  'New York': 141297, 'Florida': 170312,
                  'Illinois': 149995})
pop = pd.Series({'California': 38332521, 'Texas': 26448193,
                 'New York': 19651127, 'Florida': 19552860,
                 'Illinois': 12882135})
data = pd.DataFrame({'area':area, 'pop':pop})
data

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

The individual Series that make up the columns of the DataFrame can be accessed via dictionary-style indexing of the column name:

In [101]:
data['pop']

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
Name: pop, dtype: int64

As mentioned previously, we can also view the DataFrame as an enhanced two-dimensional array. We can examine the raw underlying data array using the values attribute:

In [102]:
data.values

array([[  423967, 38332521],
       [  695662, 26448193],
       [  141297, 19651127],
       [  170312, 19552860],
       [  149995, 12882135]])

With this picture in mind, many familiar array-like observations can be done on the DataFrame itself. For example, we can transpose the full DataFrame to swap rows and columns:

In [103]:
data.T

California     Texas  New York   Florida  Illinois
area      423967    695662    141297    170312    149995
pop     38332521  26448193  19651127  19552860  12882135

When it comes to indexing of DataFrame objects, however, it is clear that the dictionary-style indexing of columns precludes our ability to simply treat it as a NumPy array. In particular, passing a single index to an array accesses a row:

In [104]:
data.values[0]

array([  423967, 38332521])

...while passing a single "index" to a DataFrame accesses a column:

In [105]:
data['area']

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
Name: area, dtype: int64

Thus, for array-style indexing, we need another convention. Here Pandas again uses the `.loc` and `.iloc` indexers mentioned earlier. Using the `.iloc` indexer, we can index the underlying array as if it is a simple NumPy array (using the implicit Python-style index), but the DataFrame index and column labels are maintained in the result:

In [106]:
data.iloc[:3, :]

area       pop
California  423967  38332521
Texas       695662  26448193
New York    141297  19651127

Similarly, using the `.loc` indexer we can index the underlying data in an array-like style but using the explicit index and column names:

In [107]:
data.loc[:'Texas', :'pop']

area       pop
California  423967  38332521
Texas       695662  26448193

We can also pass conditions to the indexer, a technique called **masking**.

In [108]:
# masking with .loc
data.loc[data.area > 200000]

area       pop
California  423967  38332521
Texas       695662  26448193

In [109]:
# masking with explicit column index
new_df = data[data["area"] > 200000]
new_df

area       pop
California  423967  38332521
Texas       695662  26448193

Masks are conditional statements that are evaluated for every element (i.e., row) of the DataFrame.
If you want to combine multiple statements, you can use boolean operators: `&`, `|`. Negation is handled with `~` in pandas masking. Be aware that you cannot use operators such as `and`, `or`, `!`, `not`.

In [110]:
data[(data["area"] > 100000) & (data["area"] <= 180000)]

area       pop
New York  141297  19651127
Florida   170312  19552860
Illinois  149995  12882135

Any of these indexing conventions may also be used to set or modify values; this is done in the standard way that you are accustomed to from working with NumPy:

In [111]:
data.iloc[0, 1] = 90000000
data

area       pop
California  423967  90000000
Texas       695662  26448193
New York    141297  19651127
Florida     170312  19552860
Illinois    149995  12882135

### Data anaylsis and manipulation in `Pandas`

#### Hierarchical Indexing

**Using MultiIndex to create hierarchichal DataFrames**

Often it is useful to store higher-dimensional data, i.e. data indexed by more than one or two keys. The most approapriate Pandas function for this is `MultiIndex`. We will demonstrate using a simple example:

In [112]:
# we use a 2-D example, first specifying the outer and inner dimensions as well as the values
Outer = ['California','California',
         'New York','New York',
         'Texas','Texas']

Inner = [2000,2010,
         2000,2010,
         2000,2010]

populations = [33871648, 37253956,
               18976457, 19378102,
               20851820, 25145561]

# From the outer and inner dimensions we create an index
index_list = list(zip(Outer,Inner))
index_list

[('California', 2000),
 ('California', 2010),
 ('New York', 2000),
 ('New York', 2010),
 ('Texas', 2000),
 ('Texas', 2010)]

In [113]:
# based on this index a multi index can be created
index_object = pd.MultiIndex.from_tuples(index_list)
index_object

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

You can generate the same result using the `MultiIndex.from_arrays()` function fro **Pandas**. Keep in mind the size of arrays has to be the same.

In [114]:
mul_ind = pd.MultiIndex.from_arrays([Outer, Inner])
mul_ind

MultiIndex([('California', 2000),
            ('California', 2010),
            (  'New York', 2000),
            (  'New York', 2010),
            (     'Texas', 2000),
            (     'Texas', 2010)],
           )

In [115]:
# Finally we create a data frame with hierarchichal indexes
df = pd.DataFrame(index=index_object,
                  data=populations,
                  columns=["Population"])

df

Population
California 2000    33871648
           2010    37253956
New York   2000    18976457
           2010    19378102
Texas      2000    20851820
           2010    25145561

In [116]:
area = [164,164, #California 
        55,55,   #NY State
        269,269] #Texas

df["Area"] = area

df

Population  Area
California 2000    33871648   164
           2010    37253956   164
New York   2000    18976457    55
           2010    19378102    55
Texas      2000    20851820   269
           2010    25145561   269

In [117]:
# again, we can easily transpose this DataFrame
df.transpose()

California            New York               Texas          
                 2000      2010      2000      2010      2000      2010
Population   33871648  37253956  18976457  19378102  20851820  25145561
Area              164       164        55        55       269       269

**MultiIndex as extra dimension**

You might notice that we could have stored the same data using a simple DataFrame with index and column labels. The `unstack()` method allows us to convert a hierachically indexed Series into a conventionally indexed DataFrame.

In [118]:
df.unstack()["Population"]

2000      2010
California  33871648  37253956
New York    18976457  19378102
Texas       20851820  25145561

Pivot a level of the (necessarily hierarchical) index labels, returning
a DataFrame having a new level of column labels whose inner-most level
consists of the pivoted index labels.

In [119]:
df.unstack(level = -1)

Population           Area     
                 2000      2010 2000 2010
California   33871648  37253956  164  164
New York     18976457  19378102   55   55
Texas        20851820  25145561  269  269

#### Merging data in `Pandas`

Pandas also makes it easy to combine a Series and DataFrame. Multiple Series can be joined to represent a DataFrame, while multiple DataFrame can be joined in a table style join (like in databases):

In [120]:
s1 = pd.Series([1,1,2,2,3,3], name = 'Series 1')
s2 = pd.Series([1.1, 1.2, 2.2, 2.4, 3.3, 3.6], name = 'Series 2')
 
pd.DataFrame([s1, s2])

0    1    2    3    4    5
Series 1  1.0  1.0  2.0  2.0  3.0  3.0
Series 2  1.1  1.2  2.2  2.4  3.3  3.6

If we want them to represent columns, we need to supply them as values of a dictionary indexed by column names:

In [121]:
s1s2 = pd.DataFrame({'Series 1': s1, 'Series 2': s2})
s1s2

Series 1  Series 2
0         1       1.1
1         1       1.2
2         2       2.2
3         2       2.4
4         3       3.3
5         3       3.6

In [122]:
# merge series objects by index
pd.merge(s1s2, s1, left_index=True, right_index=True)

Series 1_x  Series 2  Series 1_y
0           1       1.1           1
1           1       1.2           1
2           2       2.2           2
3           2       2.4           2
4           3       3.3           3
5           3       3.6           3

Here, we join on the index, but we could also join on another column:

In [123]:
a = pd.DataFrame({
    'key': [1,2,4,5,5,6],
    'value': [0.1, 0.2, 0.4, 0.5, 0.55, 0.6]
})

b = pd.DataFrame({
    'key': [1,2,4,5,5,6],
    'value': pd.Series([0.1, 0.2, 0.4, 0.5, 0.55, 0.6]) ** 2
})

pd.merge(a, b, on = 'key')

key  value_x  value_y
0    1     0.10   0.0100
1    2     0.20   0.0400
2    4     0.40   0.1600
3    5     0.50   0.2500
4    5     0.50   0.3025
5    5     0.55   0.2500
6    5     0.55   0.3025
7    6     0.60   0.3600

Observe that there are more rows than in each of the individual DataFrames. This is because we do an inner style join, where we return every match, and the key `5` matches four times, as it is present two times in both DataFrames!

#### Quick data analysis in `Pandas`

In practice your dataset will often be considerably larger than the illustrative example above. In these cases it is often useful to run brief descriptive statistical analyses on the set, which will help to get a first feel for the data. 

We will demonstrate how to do this using the provided `iris.csv` dataset. This is a famous dataset used frequently for educational purposes in data science. You can read up on the dataset, its content and its origins here: https://en.wikipedia.org/wiki/Iris_flower_data_set.

The iris dataset contains measurements for 150 iris flowers from three different species.

The __three classes__ in the Iris dataset:
* Iris-setosa (n=50)
* Iris-versicolor (n=50)
* Iris-virginica (n=50)

The __four features__ of the Iris dataset:
* sepal length in cm
* sepal width in cm
* petal length in cm
* petal width in cm

<img src="./iris.original.png" width="600" height="400"/>

In [124]:
# first read in the data as a dataframe
# you can optionally set the index by using the index_col function
Iris_set = pd.read_csv("../data/iris.csv", index_col="number")

In [125]:
Iris_set.columns

Index(['Sepal.Length', 'Sepal.Width', 'Petal.Length', 'Petal.Width',
       'Species'],
      dtype='object')

In [126]:
# display the first five columns
Iris_set.head()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width Species
number                                                              
1                5.1          3.5           1.4          0.2  setosa
2                4.9          3.0           1.4          0.2  setosa
3                4.7          3.2           1.3          0.2  setosa
4                4.6          3.1           1.5          0.2  setosa
5                5.0          3.6           1.4          0.2  setosa

In [127]:
# display the last 5 columns
Iris_set.tail()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
number                                                                 
146              6.7          3.0           5.2          2.3  virginica
147              6.3          2.5           5.0          1.9  virginica
148              6.5          3.0           5.2          2.0  virginica
149              6.2          3.4           5.4          2.3  virginica
150              5.9          3.0           5.1          1.8  virginica

In [128]:
# the describe function provides an overview of key descriptive statistics by columns
Iris_set.describe()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
count    146.000000   148.000000    147.000000   149.000000
mean       5.832877     3.059459      3.734694     1.191946
std        0.819345     0.435943      1.775196     0.759402
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.550000     0.300000
50%        5.800000     3.000000      4.300000     1.300000
75%        6.400000     3.325000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [129]:
# get info on data types and counts
Iris_set.info()

<class 'pandas.core.frame.DataFrame'>
Index: 150 entries, 1 to 150
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Sepal.Length  146 non-null    float64
 1   Sepal.Width   148 non-null    float64
 2   Petal.Length  147 non-null    float64
 3   Petal.Width   149 non-null    float64
 4   Species       150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 7.0+ KB


In [130]:
# you can also focus your analysis on individual features by indexing them
Iris_set["Sepal.Width"].describe()

count    148.000000
mean       3.059459
std        0.435943
min        2.000000
25%        2.800000
50%        3.000000
75%        3.325000
max        4.400000
Name: Sepal.Width, dtype: float64

In [131]:
# additionally you can call the functions seperately, e.g. max
Iris_set.max()

Sepal.Length          7.9
Sepal.Width           4.4
Petal.Length          6.9
Petal.Width           2.5
Species         virginica
dtype: object

#### Handling missing numerical data (`NaN` values)
If you have paid attention to the descriptive statistics above you will have noticed that the __counts__ of values differ across features. This is a first indication for missing numerical data. In the real world you will often encounter incomplete and noisy data which will require pre-processing before you can apply data science and machine learning tools to them. In this section we will provide a quick overview on how to deal with missing data in your datasets. 
Note that there are multiple ways how Python, Pandas, and other packages might highlight missing data:
* `NaN` - (acronym for Not a Number), is a special floating-point value recognized by all systems that use the standard IEEE floating-point representation. Pandas uses this for display
* `pd.NA` - is a special pandas type, that is shorthand for all other types
* `None` - Python-specific object that is often used for missing data in Python code. Because it is a Python object, `None` can only be used in arrays with data type 'object' (i.e., arrays of Python objects)

**Detecting missing numerical data**

Pandas data structures have two useful methods for detecting null data: `isnull()` and `notnull()`. Either one will return a Boolean mask over the data.

In [132]:
# isnull() returns "True" for every missing numerical value in the dataset
Iris_set.isnull()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
number                                                               
1              False        False         False        False    False
2              False        False         False        False    False
3              False        False         False        False    False
4              False        False         False        False    False
5              False        False         False        False    False
...              ...          ...           ...          ...      ...
146            False        False         False        False    False
147            False        False         False        False    False
148            False        False         False        False    False
149            False        False         False        False    False
150            False        False         False        False    False

[150 rows x 5 columns]

In [133]:
# notnull() returns "False" for every missing numerical value in the dataset
Iris_set.notnull()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width  Species
number                                                               
1               True         True          True         True     True
2               True         True          True         True     True
3               True         True          True         True     True
4               True         True          True         True     True
5               True         True          True         True     True
...              ...          ...           ...          ...      ...
146             True         True          True         True     True
147             True         True          True         True     True
148             True         True          True         True     True
149             True         True          True         True     True
150             True         True          True         True     True

[150 rows x 5 columns]

#### Dealing with missing numerical data
In essence two approaches to dealing with missing data exist:
* __Elimination__: Dropping null values from the dataset
* __Imputation__: Imputing/replacing null values with numerical values/estimates

**Elimination (i.e. dropping null values)**

We cannot drop single values from a data frame; we can only drop full rows or full columns. Depending on the application, you might want one or the other, so `dropna()` gives a number of options:

We use the `dropna(axis=0)` function to drop all rows from the dataset that incl. null values. Note that `dropna()` will not modify your dataframe unless you call `dropna(axis=0,inplace=True)`

In [134]:
Iris_set.dropna(axis=0, inplace=False)

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
number                                                                 
1                5.1          3.5           1.4          0.2     setosa
2                4.9          3.0           1.4          0.2     setosa
3                4.7          3.2           1.3          0.2     setosa
4                4.6          3.1           1.5          0.2     setosa
5                5.0          3.6           1.4          0.2     setosa
...              ...          ...           ...          ...        ...
146              6.7          3.0           5.2          2.3  virginica
147              6.3          2.5           5.0          1.9  virginica
148              6.5          3.0           5.2          2.0  virginica
149              6.2          3.4           5.4          2.3  virginica
150              5.9          3.0           5.1          1.8  virginica

[140 rows x 5 columns]

In [135]:
# note that the dataset is unchanged
Iris_set

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width    Species
number                                                                 
1                5.1          3.5           1.4          0.2     setosa
2                4.9          3.0           1.4          0.2     setosa
3                4.7          3.2           1.3          0.2     setosa
4                4.6          3.1           1.5          0.2     setosa
5                5.0          3.6           1.4          0.2     setosa
...              ...          ...           ...          ...        ...
146              6.7          3.0           5.2          2.3  virginica
147              6.3          2.5           5.0          1.9  virginica
148              6.5          3.0           5.2          2.0  virginica
149              6.2          3.4           5.4          2.3  virginica
150              5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

We use the `dropna(axis=1)` function to drop all columns from the dataset that incl. null values. Note that, also in this case, `dropna()` will not modify your dataframe unless you call `dropna(axis=1,inplace=True)`

In [136]:
Iris_set.dropna(axis=1)

Species
number           
1          setosa
2          setosa
3          setosa
4          setosa
5          setosa
...           ...
146     virginica
147     virginica
148     virginica
149     virginica
150     virginica

[150 rows x 1 columns]

In [137]:
# again, note that dropna() does not modify the original dataframe!
len(Iris_set)

150

In [138]:
# we can therefore also use dropna() to easily identify the number of rows with missing values 
len(Iris_set)-len(Iris_set.dropna())

10

In [139]:
# if you whish to clean the data with dropna it is good practice to define a new data frame
Iris_set_clean = Iris_set.dropna(axis=0)

In [140]:
len(Iris_set_clean)

140

**Imputation (i.e. filling null values)**

Imputation fills null values with numerical values chosen by the data scientist. For this `fillna()`provides the appropriate tools.

The data scientist will usually choose one of the following methods:
* Fill with zeros: `fillna(0)`
* Conduct a forward fill (i.e. filling NaN values with data from following observation): `fillna(method="ffill")`
* Conduct a backward fill (i.e. filling NaN values with data from previous observation): `fillna(method="bfill")`
* Fill with the column mean,max,min, etc.: `df["Col_name"].fillna(value=df["Col_name"].mean())`
* Custom fill depending on the application

In [141]:
# fillna() allows for inserting a number of choice, confirm with inplace=True
Iris_set[["Sepal.Length"]].fillna(value=Iris_set["Sepal.Length"].mean())

Sepal.Length
number              
1                5.1
2                4.9
3                4.7
4                4.6
5                5.0
...              ...
146              6.7
147              6.3
148              6.5
149              6.2
150              5.9

[150 rows x 1 columns]

#### Data aggregation and grouping
The `groupby()` method allows for grouping of rows and the application of aggregation functions to these grouped rows. It is a highly popular method in data science used extensively. We will return to the iris dataset for illustration purposes.

In [142]:
# we might want to group rows according to "Species" and assign to a new variable "Species_group"
Species_groups = Iris_set.groupby("Species").describe()
Species_groups

Sepal.Length                                                \
                  count      mean       std  min   25%  50%  75%  max   
Species                                                                 
setosa             49.0  5.010204  0.354874  4.3  4.80  5.0  5.2  5.8   
versicolor         50.0  5.936000  0.516171  4.9  5.60  5.9  6.3  7.0   
virginica          47.0  6.580851  0.629920  4.9  6.25  6.5  6.9  7.9   

           Sepal.Width            ... Petal.Length      Petal.Width            \
                 count      mean  ...          75%  max       count      mean   
Species                           ...                                           
setosa            49.0  3.430612  ...        1.575  1.9        50.0  0.246000   
versicolor        50.0  2.770000  ...        4.600  5.1        50.0  1.326000   
virginica         49.0  2.983673  ...        5.900  6.9        49.0  2.020408   

                                               
                 std  min  25%  50%  75%  max  
Species                                        
setosa      0.105386  0.1  0.2  0.2  0.3  0.6  
versicolor  0.197753  1.0  1.2  1.3  1.5  1.8  
virginica   0.274605  1.4  1.8  2.0  2.3  2.5  

[3 rows x 32 columns]

In [143]:
# we might select an individual group across all features
# note that you need to transpose the array before you can index the group
Iris_set.groupby("Species").describe().transpose()[["versicolor"]]

Species             versicolor
Sepal.Length count   50.000000
             mean     5.936000
             std      0.516171
             min      4.900000
             25%      5.600000
             50%      5.900000
             75%      6.300000
             max      7.000000
Sepal.Width  count   50.000000
             mean     2.770000
             std      0.313798
             min      2.000000
             25%      2.525000
             50%      2.800000
             75%      3.000000
             max      3.400000
Petal.Length count   49.000000
             mean     4.255102
             std      0.473489
             min      3.000000
             25%      4.000000
             50%      4.300000
             75%      4.600000
             max      5.100000
Petal.Width  count   50.000000
             mean     1.326000
             std      0.197753
             min      1.000000
             25%      1.200000
             50%      1.300000
             75%      1.500000
             max      1.800000

You can also apply aggregation functions to each group using groupby-apply syntax:

In [144]:
Iris_set.groupby("Species").max()

Sepal.Length  Sepal.Width  Petal.Length  Petal.Width
Species                                                         
setosa               5.8          4.4           1.9          0.6
versicolor           7.0          3.4           5.1          1.8
virginica            7.9          3.8           6.9          2.5

Here, we applied the `max` aggregation function to all groups, but we can restrict that to columns and even use different aggregation functions per column of interest using the more flexible `agg` functionality. We need to give the desired aggregation function for every column, and columns we don't explicitly list get omitted in aggregation:

In [145]:
Iris_set.groupby("Species").agg({'Sepal.Length': 'min', 'Sepal.Width': 'max', 'Petal.Length': 'median'})

Sepal.Length  Sepal.Width  Petal.Length
Species                                            
setosa               4.3          4.4           1.5
versicolor           4.9          3.4           4.3
virginica            4.9          3.8           5.6

You can check which functions are available by looking at the [Documentation](https://pandas.pydata.org/docs/user_guide/groupby.html#built-in-aggregation-methods).

Sometimes you might wish to give the resulting columns names that reflect what aggregation you used. You can use named aggregation for that, but must then use keyword arguments instead of passing a dictionary:

In [146]:
df = pd.DataFrame({
    'group': ['A', 'A', 'B', 'C', 'C', 'C'],
    'somevalue': [1, 2, 1.5, 1, 2, 3],
    'anothervalue': [1.1, 2.1, 1.6, 1.1, 2.1, 3.1]
})

In [147]:
df.groupby('group').agg(
    somevalue_avg = pd.NamedAgg(column='somevalue', aggfunc='mean'), 
    anothervalue_max = pd.NamedAgg(column='anothervalue', aggfunc='max'),     
)

somevalue_avg  anothervalue_max
group                                 
A                1.5               2.1
B                1.5               1.6
C                2.0               3.1

Unluckily, this only works if the new column names are valid Python keywords, which would for example not be the case when we want to name resulting columns in our flower example using the syntax `agg.columnname`. 

In [ ]:
Iris_set.groupby("Species").agg(
    avg.Sepal.Length = pd.NamedAgg(column='Sepal.Length', aggfunc='mean'),
    median.Sepal.Length = pd.NamedAgg(column='Sepal.Length', aggfunc='median')
)

Here, we need a little trick (which is presented in the pandas documentation [here](https://pandas.pydata.org/docs/user_guide/groupby.html#named-aggregation)): Python functions accept a dynamic unpacking of dictionaries for keyword arguments (`**kwargs`), which is why we can circumvent the illegal named aggregation:

In [149]:
Iris_set.groupby("Species").agg(
    **{
    'avg.Sepal.Length': pd.NamedAgg(column='Sepal.Length', aggfunc='mean'),
    'median.Sepal.Length': pd.NamedAgg(column='Sepal.Length', aggfunc='median')
    }
)

avg.Sepal.Length  median.Sepal.Length
Species                                          
setosa              5.010204                  5.0
versicolor          5.936000                  5.9
virginica           6.580851                  6.5

**Final note**:
To add a table of content to your jupyter notebook, you need to install the `nbextension` available on https://github.com/minrk/ipython_extensions.

---